### ISSUE TITLE
some demo?

### ISSUE THREAD

**Issue by andzi** [adonald/Pantone-CMYK-RGB-Hex#1]
Some demo would be nice, isn't?

**Comment by adonald** [comment]
The code includes a self contained HTML file, referenced in the readme, that demonstrates the output. It is also hosted on my website under the "projects" section.

**Comment by Arhurweb** [comment]
Very cool, but i compare codes RGB and pantone, and did't match any code with the colors. I will try to help very soon.
Thank you!
